@baseUrl = http://localhost:3333

# Criar uma conta
Post {{baseUrl}}/accounts
Content-Type: application/json

{
    "name": "Jamal",
    "email": "jamal@gmail.com",
    "password": "123456"
}

###

# Autenticar
Post {{baseUrl}}/sessions
Content-Type: application/json

{
    "email": "jamal@gmail.com",
    "password": "123456"
}

