@baseUrl = http://localhost:3333
@authToken = {{{{authenticate.response.body.access_token}}}}

# @name create_account
Post {{baseUrl}}/accounts
Content-Type: application/json

{
    "name": "Jamal",
    "email": "jamal200@gmail.com",
    "password": "123456"
}

###

# @name authenticate
Post {{baseUrl}}/sessions
Content-Type: application/json

{
    "email": "jamal200@gmail.com",
    "password": "123456"
}

###

# @name create_question
Post {{baseUrl}}/questions
Content-Type: application/json
Authorization: Bearer {{authToken}}




