version: '3.8'

services:
  postgres:
    container_name: api-nest-clean
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: api-nest-clean
      PGDATA: /data/postgres
    ports:
      - '5432:5432'
    volumes:
      - ./data/pg:/data/postgres
